// Snapshot de Ondo Stocks en Solana, generado por scripts/gen-ondo-seed.mjs; no editar a mano.
// Fuente única de mints Ondo: data/ondo/ondo-vs-xstocks-2026-10-07.csv.
// Símbolo `<TICKER>on`. Entran en `watch` (migración 0022, sin aplicar).

export interface OndoEntry {
  /** Símbolo en el catálogo (`<TICKER>on`). */
  symbol: string;
  /** Ticker del subyacente (agrupa por empresa: `company_ticker`). */
  ticker: string;
  name: string;
  /** Mint en Solana (registro oficial de Ondo, vía el CSV). */
  mint: string;
  kind: "stock" | "etf";
  /** Columna `ganador` del CSV: sólo desempate por volumen. */
  winner: string;
  volumeWinner: "xstocks" | "ondo" | null;
}

export const ONDO_TICKERS: OndoEntry[] = [
  { symbol: "AALon", ticker: "AAL", name: "American Airlines Group", mint: "9wYZetvT8J2ptfsRca5gzLBGvcUug38mp9yT3xaondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "AAOIon", ticker: "AAOI", name: "Applied Optoelectronics", mint: "YuFZvc8JCN3a6BUAqwnbY4AnhuVEXD4V7QnBTmwondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "AAONon", ticker: "AAON", name: "AAON", mint: "nwPWRVFCbU3cdXWdJsuwomC5u459xPFdP2vYsmVondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "AAPLon", ticker: "AAPL", name: "Apple", mint: "123mYEnRLM2LLYsJW3K6oyYh8uP1fngj732iG638ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "ABBVon", ticker: "ABBV", name: "AbbVie", mint: "MFerpBVGKZh2jXN7cbJdXRXQTp6j6pbSnSZrfWrondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "ABNBon", ticker: "ABNB", name: "Airbnb", mint: "128qNYovdGv2YqayErcJgU7gDwbNVX1VuoxbtWz8ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "ABTon", ticker: "ABT", name: "Abbott", mint: "129gRoHKhVg7CvPMrqVsEB4uYZo6zV4yDZX6NBg9ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "ACHRon", ticker: "ACHR", name: "Archer Aviation", mint: "KcCVQxG9LhFYP5o9DWFKTFgFShPPQkDEemVbiFyondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "ACLSon", ticker: "ACLS", name: "Axcelis Technologies", mint: "jDoTgDRKSgVzkKdkaHZL3DiVmDM4YtYWwRG6Tgfondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "ACMRon", ticker: "ACMR", name: "ACM Research", mint: "nkbH2doD7nU4CkKVwzmd6UV4d2AaGy24NHzsh6tondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "ACNon", ticker: "ACN", name: "Accenture", mint: "12LxMMJYVSf4LoeqjFE47BQQNRciaH9E3nbDfjH4ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "ADBEon", ticker: "ADBE", name: "Adobe", mint: "12Rh6JhfW4X5fKP16bbUdb4pcVCKDHFB48x8GG33ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "ADIon", ticker: "ADI", name: "Analog Devices", mint: "LmTMwmZLNZszn3qpjmnbhfP12U4qWDivaEBwSBSondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "AEHRon", ticker: "AEHR", name: "Aehr Test Systems", mint: "ZWUSgDGQTQPGJyipzgJKcPhxgZzSBi4q6dqQbgCondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "AGon", ticker: "AG", name: "First Majestic Silver", mint: "hrZ5vs6c6v1iWyvEXjGSHs3sQuuj58VzXikNyRWondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "AGGon", ticker: "AGG", name: "iShares Core US Aggregate Bond ETF", mint: "13qTjKx53y6LKGGStiKeieGbnVx3fx1bbwopKFb3ondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "AIPon", ticker: "AIP", name: "Arteris", mint: "jmnrdSzu293vKTWyEx3A2ZRVxxytJKW1wD3CLzkondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "AIQon", ticker: "AIQ", name: "Global X Artificial Intelligence & Technology ETF", mint: "uwh6Z6c2F8WZfUSK1A8VBfA9AwJKN5T2bvQwVFLondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "ALABon", ticker: "ALAB", name: "Astera Labs", mint: "cskxd6aqyqJMYgLZmFYfYecWkjasRJDEtm1QVxsondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "ALBon", ticker: "ALB", name: "Albemarle", mint: "B5KufqHkskgGYwMXtL8FSHgREAkMQvE3ykhH5Kmondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "ALOYon", ticker: "ALOY", name: "REalloys", mint: "ndHvUEgrvZquSR6wZv2cG1AiBr7e7HGuWvfPULcondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "AMATon", ticker: "AMAT", name: "Applied Materials", mint: "7eRX747PSbVtGVx3qD5UFdkNM2BfTy86ikUiCMhondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "AMCon", ticker: "AMC", name: "AMC Entertainment", mint: "C9xNaNujcF1a5fidWAAFReFYqhLRVbyk4yPyGqzondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "AMDon", ticker: "AMD", name: "AMD", mint: "14diAn5z8kjrKwSC8WLqvBqqe5YmihJhjxRxd8Z6ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "AMEon", ticker: "AME", name: "AMETEK", mint: "ko48myqhBuXyL9WAp6pTzHWsdKsGKSditJVoGTSondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "AMGNon", ticker: "AMGN", name: "Amgen", mint: "SS6AEWhzRrxhL2cXzKKjhFt3rCzmHHGKmFyugDTondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "AMKRon", ticker: "AMKR", name: "Amkor Technology", mint: "nvvoP8gFyY2aZp6Cxu9Qq4MQqGrMebjtCxWrYfbondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "AMZNon", ticker: "AMZN", name: "Amazon", mint: "14Tqdo8V1FhzKsE3W2pFsZCzYPQxxupXRcqw9jv6ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "ANETon", ticker: "ANET", name: "Arista Networks", mint: "Cq6QtvHpXbJWtFaiMhUDtHy8YVZ95gcD1oZ1cohondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "AOSLon", ticker: "AOSL", name: "Alpha and Omega Semiconductor", mint: "b98FynyBEkdhP4Y3QUvKG36nms4oMsxEZUrCBMvondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "APHon", ticker: "APH", name: "Amphenol", mint: "fFTZ9Jckm2X811mdqRBS4ckMz5bRAJVjH4Jwofwondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "APLDon", ticker: "APLD", name: "Applied Digital", mint: "B6WqvLGXdGqpw7qgxeb5EGiRZEYo2apWpQybjYuondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "APOon", ticker: "APO", name: "Apollo Global Management", mint: "14VXAhoa1R74vi1ZuiQyGLJrnDMfoFBPJSCpGVz3ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "APPon", ticker: "APP", name: "AppLovin", mint: "14Z8rQQe2Aza33YgEUmj3g3QGNz8DXLiFPuCnsD1ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "ARGTon", ticker: "ARGT", name: "Global X MSCI Argentina ETF", mint: "rki25TZmDh94spjeoyyGWjkVEYSzcVvaAbddXGuondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "ARMon", ticker: "ARM", name: "Arm Holdings plc", mint: "15SsCZqCsM9fZGhTmP4rdJTPT9WGZKazDSsgeQ8ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "ARQQon", ticker: "ARQQ", name: "Arqit Quantum", mint: "crakmaGKTuVRYqSBsFsuqio5CmpEQnpibDrVLbDondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "ASMLon", ticker: "ASML", name: "ASML Holding NV", mint: "1eLZPRsn8bAKmoxsqDMH9Q2m2k7GMNp6RLSQGm8ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "ASTSon", ticker: "ASTS", name: "AST SpaceMobile", mint: "B6ry9goGNvVbhq7gWHzs3p6emJ1gLaMhu4By9TTondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "ATKRon", ticker: "ATKR", name: "Atkore", mint: "ZsCDHjWFyndwgbHMs4AHYwJZQMgmAn72ESQj2b5ondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "AURon", ticker: "AUR", name: "Aurora Innovation", mint: "eGbh3V9R5ujWYwKJZAyM4Eg3sfzLhwKyr4bGbTsondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "AVGOon", ticker: "AVGO", name: "Broadcom", mint: "1FWZtdWN7y38BSXGzbs8D6Shk88oL9atDNgbVz9ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "AXPon", ticker: "AXP", name: "American Express", mint: "1WxT6NdK7uqpfXuKpALxL2n3f7Rq61XXeHA8UM4ondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "AXTIon", ticker: "AXTI", name: "AXT", mint: "Z1K14ngynqmrmfRSC2dRZGs1ghmnDKiiahjaM2condo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "BAon", ticker: "BA", name: "Boeing", mint: "1YVZ4LGpq8CAhpdpm3mgy7GgPb83gJczCpxLUQ3ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "BABAon", ticker: "BABA", name: "Alibaba", mint: "1zvb9ELBFShBCWKEk5jRTJAaPAwtVt7quEXx1X4ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "BACon", ticker: "BAC", name: "Bank of America", mint: "Wk8gC6iTNp8dqd4ghkJ3h1giiUnyhykwHh7tYWjondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "BAIon", ticker: "BAI", name: "iShares A.I. Innovation and Tech Active ETF", mint: "gKkrSgVjRjdQX4LFErBka1izQhoW2VHXFcCS5Vbondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "BBAIon", ticker: "BBAI", name: "BigBear.ai Holdings", mint: "YXE7mph6XhsgnyezkMEcTuohSuWhbLWfwx2Hh6mondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "BEon", ticker: "BE", name: "Bloom Energy", mint: "bBMTGF7atoCizHMT3KCeqJzqR2gXFSUXr53AEDgondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "BIDUon", ticker: "BIDU", name: "Baidu", mint: "54CoRF2FYMZNJg9tS36xq5BUcLZ7rju1r59jGc2ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "BILon", ticker: "BIL", name: "SPDR Bloomberg 1-3 Month T-Bill ETF", mint: "wtwpt5yJbButAhjpYhtg4uvUgCQN4LVgvLq2AxEondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "BILIon", ticker: "BILI", name: "Bilibili", mint: "14kLsQVmc64qZexYuR4XGop9y8BeMkd77pJUm1Rhondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "BINCon", ticker: "BINC", name: "iShares Flexible Income Active ETF", mint: "mhZ69E1vDnAsQJXAwarLYSX5tmgeMajXBJ2rXAcondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "BKCHon", ticker: "BKCH", name: "Global X Blockchain ETF", mint: "uyWDgDZqL6x2V86i7vwJTKPuyg2u79UYaBe5yt7ondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "BLCRon", ticker: "BLCR", name: "iShares Large Cap Core Active ETF", mint: "g3jQMP79SxnH1KisVw3C4SBpa8gSbPAocNJruJFondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "BLKon", ticker: "BLK", name: "Blackrock, Inc.", mint: "5H1VpMzRuoNtRbPTRCz35ETtEUtnkt8hJuQb9v7ondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "BLSHon", ticker: "BLSH", name: "Bullish", mint: "A9PFmw9Hu8zzxDUoU351pio1E1XWBWBfWnjT9qoondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "BMNRon", ticker: "BMNR", name: "BitMine Immersion Technologies", mint: "MYXqkDYbzr7vjXAz2BapR4AiYRXzoikGirrLoRzondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "BNOon", ticker: "BNO", name: "US Brent Oil Fund", mint: "BAU83kqEqhyiexfAMQhZZE5KnGogSqh17fJc44Sondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "BOTon", ticker: "BOT", name: "RoboStrategy", mint: "b8UDyp3Yx19rcdaBUNegoojyUdhPpiPQ46bFrtQQQon", kind: "stock", winner: "ninguno", volumeWinner: null },
  { symbol: "BOTZon", ticker: "BOTZ", name: "Global X Robotics & Artificial Intelligence ETF", mint: "soLM6jRVdG1PdurSAQDz5qRtwWxXPM6EBvwrkBjondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "BRHYon", ticker: "BRHY", name: "iShares High Yield Active ETF", mint: "fznj92AnTcQ6mAFvt68JgLJS5pHag5uPmJ7LmSLondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "BRLNon", ticker: "BRLN", name: "iShares Floating Rate Loan Active ETF", mint: "fcfpT8y5fpEBJjqmjKLpscZYzVjxR95ErJsb31jondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "BRTRon", ticker: "BRTR", name: "iShares Total Return Active ETF", mint: "gPwmyo4BM4qgYYCTVgA4eJmzsnYNVMUJYBecYkCondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "BTDRon", ticker: "BTDR", name: "Bitdeer Technologies", mint: "kBUAHgGHFthfnwarWxqYxHqVDnqqieJkXb6kvroondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "BTGon", ticker: "BTG", name: "B2Gold", mint: "cBnVXDyZgaaLZM18wAmqsUKnRUFAEJWbq6VuUoaondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "BTGOon", ticker: "BTGO", name: "BitGo Holdings", mint: "bgJWGuQxyoyFeXwzYZKBmoujVdatGFYPNFnv1a6ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "BWETon", ticker: "BWET", name: "Breakwave Tanker Shipping ETF", mint: "m7mWfvhyPikY3esNwTk8U1JRbcBijmzHgqiqx3xondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "BZon", ticker: "BZ", name: "Kanzhun", mint: "doPqjCxi6UkANkvMz5fSuYGEo5PGppVpTZMeB5vondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "Con", ticker: "C", name: "Citigroup", mint: "PjtfUiw6Hwd8PZ94EcUw8mBSYxp7SjjzSLeNTDKondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "CAMTon", ticker: "CAMT", name: "Camtek", mint: "ZcS6FuJ1nAjgwJejUsxkasM6JpEDkdowVyohBCzondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "CAPRon", ticker: "CAPR", name: "Capricor Therapeutics", mint: "BS8zoc6pmALQnBhBDFak6eFhgGHjpebnHzsxApgondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "CATon", ticker: "CAT", name: "Caterpillar", mint: "AErxJJxGbc9cZzZoZepN62BNfg5RXns8tmEc3Zpondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "CBRSon", ticker: "CBRS", name: "Cerebras Systems", mint: "c7KEKjzaTQYpTrHM2db8yq3bikPpcXrHgBV8Qcgondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "CCJon", ticker: "CCJ", name: "Cameco", mint: "fVPj4hHHVEeUrzVnad5fvxFEPGAXD5X6wkw1Xjdondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "CEGon", ticker: "CEG", name: "Constellation Energy", mint: "7NWHifsBnn9DimUeNnsHdEXkTZhXmJTiXxcCngBondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "CEVAon", ticker: "CEVA", name: "CEVA", mint: "nLTgFdT7x37oXMbZoZxbQ1787qSPVRLXo7JPRkLondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "CIBRon", ticker: "CIBR", name: "First Trust NASDAQ Cybersecurity ETF", mint: "BVdL3WUxtxUD4vXRWwqChJLbGxvfzZjBGPp63Wtondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "CIENon", ticker: "CIEN", name: "Ciena", mint: "cY3kDrNWP6DUZcWSQmA6Y4Nf7q5qS5kZ8zF9iLnondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "CIFRon", ticker: "CIFR", name: "Cipher Mining", mint: "WNZBSkNBNP3Ct1pcFn6Fu4sZQFhnu48EsM9voCEondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "CLFon", ticker: "CLF", name: "Cleveland-Cliffs", mint: "fTuoE9pWbVK7EUpUEENBn8Vu226T7kF3YJBTRLPondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "CLOAon", ticker: "CLOA", name: "iShares AAA CLO Active ETF", mint: "t71FyTYHVkPAb5g48adDHmkVxXYbUuP2eq6jDZLondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "CLOIon", ticker: "CLOI", name: "VanEck CLO ETF", mint: "ucQ3VfWAx9pkCN4Kg84zE56FtB4FJN2kQH4ArYYondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "CLSon", ticker: "CLS", name: "Celestica", mint: "eL1buL9zFxFhfRbjMfyPu2q9HSAJkUUnHVUgkPdondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "CMGon", ticker: "CMG", name: "Chipotle", mint: "5owVsVFSHACQuippFYdLp3qWRobp2EGcwxMmsr6ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "COFon", ticker: "COF", name: "Capital One", mint: "R2uDbMtmHq5xSS5SserrovdRKdpiqnVBCd2AHLhondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "COHRon", ticker: "COHR", name: "Coherent", mint: "BXMkru8ded26p71gJ3AMMwJmwZaYYfQjRo8vbZzondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "COHUon", ticker: "COHU", name: "Cohu", mint: "jYMxpcgARQCdvQ15H1vvRCnBUbUEEQgSnS6SsfTondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "COINon", ticker: "COIN", name: "Coinbase", mint: "5u6KDiNJXxX4rGMfYT4BApZQC5CuDNrG6MHkwp1ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "COPon", ticker: "COP", name: "ConocoPhillips", mint: "X68p9qTpEMkR1TLpXUP2ZJo8PG4Qge2Y2ZLdjA2ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "COPXon", ticker: "COPX", name: "Global X Copper Miners ETF", mint: "X7j77hTmjZJbepkXXBcsEapM8qNgdfihkFj6CZ5ondo", kind: "etf", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "COROon", ticker: "CORO", name: "iShares International Country Rotation Active ETF", mint: "gNhrgh21pQozQoc7YtvhdKF7eJnSKwWa9dzHnaxondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "CORZon", ticker: "CORZ", name: "Core Scientific", mint: "f4ucqqnktrkdDAnwqcAAiA9Lggz6NAHJ3zFwipnondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "COSTon", ticker: "COST", name: "Costco", mint: "6btaz134wjHkR8sqhAYrtSM6tavftfxnRvnyMd8ondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "CPERon", ticker: "CPER", name: "US Copper Index Fund", mint: "hpkpc1Xenv5oEpVefk3woWjZa9rxaJxaEaVVA4Fondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "CPNGon", ticker: "CPNG", name: "Coupang", mint: "NKyzy31w2J7odLb2CW3Ft4fpKXkW3LBt1pvpkVLondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "CRCLon", ticker: "CRCL", name: "Circle Internet Group", mint: "6xHEyem9hmkGtVq6XGCiQUGpPsHBaoYuYdFNZa5ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "CRDOon", ticker: "CRDO", name: "Credo Technology Group Holding", mint: "d4Rc6KvP3nQT8zC86Z31zM1DJCSfUD6y424cKnZondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "CRMon", ticker: "CRM", name: "Salesforce", mint: "7D7ukbcnUNYt7Et5vtsDZhAy28MKu9pkHka1Hp9ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "CRWDon", ticker: "CRWD", name: "CrowdStrike", mint: "cdKfoNjbXgnSuxvoajhtH3uixfZhq1YXhQsS1Rwondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "CRWVon", ticker: "CRWV", name: "CoreWeave", mint: "BfPGpgNyxe6rjAru1EJarjSBAcCABuMF5L32v7nondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "CSCOon", ticker: "CSCO", name: "Cisco Systems", mint: "7DWcZE1uVc8m2mf9pV8KNov28ET7HsvHkhrhgr9ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "CVNAon", ticker: "CVNA", name: "Carvana", mint: "FGmUDXqA3AbWfo5b3NUcsvwoUFCF4tr9ea6uercondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "CVXon", ticker: "CVX", name: "Chevron", mint: "7tgKziACteG26VjV5xKufojKxwTgCFyTwmWUmz5ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "DASHon", ticker: "DASH", name: "DoorDash", mint: "83P1gCFBZfGRCwJuBt9juxJKEsZwejJoG66eTZ6ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "DBCon", ticker: "DBC", name: "Invesco DB Commodity Index Tracking Fund", mint: "td1aY5AvYQuwGD75qNq9aPipMexraN9mQXJwqifondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "DEon", ticker: "DE", name: "Deere", mint: "CqQyAZjB9LGFTG95eiadGTkfhd9QA12ProeKsQmondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "DELLon", ticker: "DELL", name: "Dell Technologies", mint: "cFDP5SsUBeKrV1RkKHdaofHBSfRW8cBd7DiaPTSLAon", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "DGRWon", ticker: "DGRW", name: "WisdomTree US Quality Dividend Growth Fund", mint: "gnoSQSNTNZHViqVfxCcPDVxcRA29mrJL7C6JqYLondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "DGXXon", ticker: "DGXX", name: "Digi Power X", mint: "jwCKwGoJfx1p4K5XCwqPrq1xyJU1g26Tmf6UcDcondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "DISon", ticker: "DIS", name: "Disney", mint: "mJf1xT3suXtkXBCfZcE9oUUuyxkvSgqYBWiX7v1ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "DNNon", ticker: "DNN", name: "Denison Mines", mint: "12J2LD3tuLfdiVKnWZMHRMrbnXDY9rM4yqVLUa5yondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "DRAMon", ticker: "DRAM", name: "Roundhill Memory ETF", mint: "oXeD5ZesXfJQ3mxtuZdMaccUsWrE8r1SnpYRP2Bondo", kind: "etf", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "DRSon", ticker: "DRS", name: "Leonardo DRS", mint: "gtKc3PtKfUH7vbvYLJ1HCRXCpQK1Wpgevn8e6gUondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "DTCRon", ticker: "DTCR", name: "Global X Data Center & Digital Infrastructure ETF", mint: "t29YBAB7g6xzgRJkzmc5NkQ7YRjE3NF8mhsLgppondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "DYNFon", ticker: "DYNF", name: "iShares US Equity Factor Rotation Active ETF", mint: "g7vMfs5FrR8JjieeGC3c9sJaYPp4G3jGPfF4tkyondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "ECHon", ticker: "ECH", name: "iShares MSCI Chile ETF", mint: "BmXVAFyfpW7VuVYeWDtbFtLx7sek2mZt3BEsGgAondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "ECOon", ticker: "ECO", name: "Okeanis Eco Tankers", mint: "mnYetf4bWKX8HihNk1XLNYj8BPPy9PdkDFPV97Zondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "EEMon", ticker: "EEM", name: "iShares MSCI Emerging Markets ETF", mint: "916SDKz7y5ZcEZC9CtnQ5Djs1Y8Yv3UAPb6bak8ondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "EFAon", ticker: "EFA", name: "iShares MSCI EAFE ETF", mint: "AbvryMGnaba9oADMZk8Vp2Av6MtczsncGyfWaC4ondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "EFVon", ticker: "EFV", name: "iShares MSCI EAFE Value ETF", mint: "uzQx2MnWr7drR5gdNXssJrFKQkLFSdw4EpfaQ5Nondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "EMRon", ticker: "EMR", name: "Emerson Electric", mint: "nNyVbs9Qty6wU2YcP5KFh4SUxNWTdPtL2W1bTMrondo", kind: "stock", winner: "ninguno", volumeWinner: null },
  { symbol: "ENBon", ticker: "ENB", name: "Enbridge", mint: "aqEnHXRnXEQwDXEiFSEU4xHziw3Fco4b5JPkTtnondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "ENLVon", ticker: "ENLV", name: "Enlivex Therapeutics", mint: "BncvtBGs4JqgYZwUoq3EN9q9HUFqJKTfWpvCsHCondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "ENPHon", ticker: "ENPH", name: "Enphase Energy", mint: "Bp26APthMuM46gMFTo5KYpo7b92GN2xSCor7f9oondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "ENTGon", ticker: "ENTG", name: "Entegris", mint: "awCwGaVNbYJH2SyQJzgE3mB54gxa6SQEZSKZaHQondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "EQIXon", ticker: "EQIX", name: "Equinix", mint: "aheEdmuryJU8ymy8LjYheZH5i2BW1UMsfuWQKD2ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "EQTon", ticker: "EQT", name: "EQT", mint: "bWrYATfytuRwGoDbpxy16aQbMbCZDv8DURuLCAhondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "ETHAon", ticker: "ETHA", name: "iShares Ethereum Trust", mint: "LitNUakTges74cjDJm6HHfFNKGPdySkp3MWSYzYondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "ETNon", ticker: "ETN", name: "Eaton", mint: "BpYiU1dBXU1fdB64jbR93wHEw3Y47QeRLZvUyLQondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "EUHYon", ticker: "EUHY", name: "iShares Euro High Yield Corporate Bond USD Hedged ETF", mint: "teUYhoQUgqsFp9ZwYBUHfuUHdVvbNx9N8spESGqondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "EWJon", ticker: "EWJ", name: "iShares MSCI Japan ETF", mint: "C6c7VcxuUYcV5YTsky5HM4PUmfwHTwsDD5DNwwPondo", kind: "etf", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "EWYon", ticker: "EWY", name: "iShares MSCI South Korea ETF", mint: "C8pSaSgjkiTWixS3GM6Hxd6HKnKrgAbY9WDgfVeondo", kind: "etf", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "EWZon", ticker: "EWZ", name: "iShares MSCI Brazil ETF", mint: "CBKcmEvVg5EgE3W5hVSPcBYWh6TFVjQwbmYod9Pondo", kind: "etf", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "EXODon", ticker: "EXOD", name: "Exodus Movement", mint: "CJRoTbu98waCCuLFfLuJ2kXawLk889fqW4UAAbwondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "EXTRon", ticker: "EXTR", name: "Extreme Networks", mint: "js1cCZRNx8ircYiQJuhBNMnsA9owr6ZLYx6z2uNondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "Fon", ticker: "F", name: "Ford Motor", mint: "5hT2o25X9tGXipwhLckaUdgnxrZ6Y8eiUwdhpLeondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "FCELon", ticker: "FCEL", name: "FuelCell Energy", mint: "dYDS22uTX8CtiyixnXY9fMVGAkxbemVAjbCaWVbondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "FCXon", ticker: "FCX", name: "Freeport-McMoRan", mint: "CY8ttw5rYCT6fFBJwqXofefqa7Ji9E8zfLmhRLmondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "FFOGon", ticker: "FFOG", name: "Franklin Focused Growth ETF", mint: "CYAwMGyuNSDu7NpuccNwcxMNS5Bu9akxU2Jooyiondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "FGDLon", ticker: "FGDL", name: "Franklin Responsibly Sourced Gold ETF", mint: "CYqLHM92EhmF83iNgfN4A1j2ckjsHigRvXu7xHCondo", kind: "etf", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "FIGon", ticker: "FIG", name: "Figma", mint: "aLDdFsr3VTUQaHFK6yNvQxztvxQ8nxW4AMuSGC7ondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "FIGRon", ticker: "FIGR", name: "Figure Technology Solutions", mint: "ZmHxc6Gt27RJKxD2ay6UL4n9yQ7mKAq4XZQUeVhondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "FLEXon", ticker: "FLEX", name: "Flex", mint: "iicfp8Efr4WfGAP9gXmYzdxmNFi1LV3iVudAmCnondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "FLHYon", ticker: "FLHY", name: "Franklin High Yield Corporate ETF", mint: "CZ3FxxSto7tsjkSkqMek1C5p3RCFFmkwKqW57nbondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "FLNCon", ticker: "FLNC", name: "Fluence Energy", mint: "bzoe1epsQLx65zmez4pWfBumYzpaFwRTvnmCjZVondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "FLQLon", ticker: "FLQL", name: "Franklin US Large Cap Multifactor Index ETF", mint: "CZ9GBn1okotqKNUUqoxk4PF2JVi59bw5GWvVo6Dondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "FNon", ticker: "FN", name: "Fabrinet", mint: "cfxyRHXjqoKN6hF3oEGu1bpEEFGcEiVXoNG4UUCondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "FORMon", ticker: "FORM", name: "FormFactor", mint: "ZDnkXeN5awDioQjP691XFLdgZwDAv19g3fCr9KWondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "FPSon", ticker: "FPS", name: "Forgent Power Solutions", mint: "m3XghfWMqmVE81LKLVxd1FVCKjqYAUxH8bMHGhzondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "FSOLon", ticker: "FSOL", name: "Fidelity Solana Fund", mint: "BJhPr9SM7uZTZXHeSLYmUk7CjGQq1esFkVxPF5tondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "FTGCon", ticker: "FTGC", name: "First Trust Global Tactical Commodity Strategy Fund", mint: "ivBnfPTyuHDNWmMSnbavckhJK6SHZW8h77nZKsEondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "FUTUon", ticker: "FUTU", name: "Futu Holdings", mint: "Ao5rKFRQ54W3DKSAtqfhBRPNHewwWRLNLao2JL9ondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "FXIon", ticker: "FXI", name: "iShares China Large-Cap ETF", mint: "CeFbGYXDmkyfo1TXXzzZ512mtnCCewNohu6V15vondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "GDon", ticker: "GD", name: "General Dynamics", mint: "hESwwvKsJH4p7Xib5rrM921Ng19cwcQGtxyrgSJondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "GEon", ticker: "GE", name: "General Electric", mint: "aTBfDuLRqYHBiG82bHA7DzwjSDTFre2dRtGH3S5ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "GEMIon", ticker: "GEMI", name: "Gemini Space Station", mint: "NrTdGMA3ujUvWXkwXyZKnhoByb32KTjRh5Vo47yondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "GEVon", ticker: "GEV", name: "GE Vernova", mint: "CgZSv89BL58ybWfWobANKEU8nV9jYfFw23G2DZEondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "GFSon", ticker: "GFS", name: "GlobalFoundries", mint: "etnBzce6pkJq67QUv78PefkVyCEaA6YBE4hvx1Gondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "GGOVon", ticker: "GGOV", name: "iShares Global Government Bond USD Hedged Active ETF", mint: "tzuC3sZnHg7spuAFhdCqivx9qtJg15qUBUpCJx1ondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "GLDon", ticker: "GLD", name: "SPDR Gold Shares", mint: "hWfiw4mcxT8rnNFkk6fsCQSxoxgZ9yVhB6tyeVcondo", kind: "etf", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "GLTRon", ticker: "GLTR", name: "abrdn Physical Precious Metals Basket Shares ETF", mint: "CgnZbDNzBfaLyJqUtd4esKLShRp7RznQuwP4uQaondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "GLWon", ticker: "GLW", name: "Corning", mint: "YQzNQh2YSFQ6nh91E8Ja71U6JuZDLap5jJCsELGondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "GLXYon", ticker: "GLXY", name: "Galaxy Digital", mint: "CkWmEM2J79k6AjAwyQVHXteFucAL1zQrKLxLqJHondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "GMEon", ticker: "GME", name: "GameStop", mint: "aznKt8v32CwYMEcTcB4bGTv8DXWStCpHrcCtyy7ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "GNRCon", ticker: "GNRC", name: "Generac Holdings", mint: "eqzwohR9oCR6sravF4y5HyUwyvCDbnfSYqiiFrXondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "GOOGon", ticker: "GOOG", name: "Alphabet Class C", mint: "jcA9zXHWuTuDFDDDDYJTNhersed1B5etkuB6X9Eondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "GOOGLon", ticker: "GOOGL", name: "Alphabet Class A", mint: "bbahNA5vT9WJeYft8tALrH1LXWffjwqVoUbqYa1ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "GRABon", ticker: "GRAB", name: "Grab Holdings", mint: "m9GcsVgdjaL3KsdtSFHimnhtsUMpTHkjtwEG4Tzondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "GRNDon", ticker: "GRND", name: "Grindr", mint: "Gc1aT3ay7FXL3qdAW7cNSXYPDsGavy7qiACuxwxondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "GSon", ticker: "GS", name: "Goldman Sachs", mint: "BchJRy2snmhJZf3rQ9LJ3ePs2BGfYgfvQNo31d2ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "HALon", ticker: "HAL", name: "Halliburton", mint: "iFcwEB2LfeYLWKgZ2vogEzC5dP7s7xbhVX81XFwondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "HDon", ticker: "HD", name: "Home Depot", mint: "MtEXKVN3Pcggy8MPA3eJr15H6SK3RXheScqj9qtondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "HIIon", ticker: "HII", name: "Huntington Ingalls Industries", mint: "h73FNVBDq95fqGBy5eunHm2FVfu2jWZNkeXHDieondo", kind: "stock", winner: "ninguno", volumeWinner: null },
  { symbol: "HIMSon", ticker: "HIMS", name: "Hims & Hers Health", mint: "bdh3njeo19d2TBLAKTGvCWdSoArfVw8uZBAJHY4ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "HIMXon", ticker: "HIMX", name: "Himax Technologies", mint: "aCx5G8ewGTSzozEn8KmSsr9cvfyFWzGnr22GjFXondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "HIVEon", ticker: "HIVE", name: "HIVE Digital Technologies", mint: "kTMQKHhnWPTvZsfiZfcdeHdG6dMgZV27wXSiC3Yondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "HLITon", ticker: "HLIT", name: "Harmonic", mint: "o3pnLke4uti6hY3LTfb2wVBpHeWG7znjJHj6VXtondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "HOODon", ticker: "HOOD", name: "Robinhood Markets", mint: "BVdXGvmgi6A9oAiwWvBvP76fyTqcCNRJMM7zMN6ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "HPEon", ticker: "HPE", name: "Hewlett Packard Enterprise", mint: "axbgKgUMscTJ34DjA69kBJuf6UYq4Pzb8B8numYondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "HSAIon", ticker: "HSAI", name: "Hesai Group", mint: "nagL8iWMNLZVuKFk3bUGDaHyT5ZY4bNfUzsdtGHondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "HTZon", ticker: "HTZ", name: "Hertz Global Holdings", mint: "QApMAZTHvfhX2dTDzM8AMyAHVyhmPVwj4oY8Jveondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "HUBBon", ticker: "HUBB", name: "Hubbell", mint: "ZmiDoowvkpp1Qgx4mmY3qtsHbNV1oE12ApKCbZNondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "HUTon", ticker: "HUT", name: "Hut 8", mint: "f7iz4BQsnjw95EUyFiBKAnKgo7oBrycfzQdtmDwondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "HYDBon", ticker: "HYDB", name: "iShares High Yield Systematic Bond ETF", mint: "71VH3YQkjqqGxzwYvGhsCsJNQYzkMo9Rg72aVxqondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "HYGon", ticker: "HYG", name: "iBoxx $ High Yield Corporate Bond ETF", mint: "c5ug15fwZRfQhhVa6LHscFY33ebVDHcVCezYpj7ondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "HYGWon", ticker: "HYGW", name: "iShares High Yield Corporate Bond BuyWrite Strategy ETF", mint: "ZKzkbFi4n3NQmRA9i5T7jVPSN2XERwxfHUf4p2pondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "HYSon", ticker: "HYS", name: "PIMCO 0-5 Year High Yield Corporate Bond Index ETF", mint: "CsN1Tyz467bSFLPGd6MJyZhPNtwDaWZtX8ixHWyondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "IALTon", ticker: "IALT", name: "iShares Systematic Alternatives Active ETF", mint: "gfKuBLive7Q35MYgxPgNx7qx524zQJ9RiDZJFZoondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "IAUon", ticker: "IAU", name: "iShares Gold Trust", mint: "M77ZvkZ8zW5udRbuJCbuwSwavRa7bGAZYMTwru8ondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "IBITon", ticker: "IBIT", name: "iShares Bitcoin Trust", mint: "6JLG8iUkAuqiBhL3j2ckDMDf5oWAa6awmyaWezKondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "IBMon", ticker: "IBM", name: "IBM", mint: "C8bZkgSxXkyT1RgxByp2teJ24hgimPLoyEYoNa9ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "ICHRon", ticker: "ICHR", name: "Ichor Holdings", mint: "ZTABSukbFUFcuCYpMFHxN18aB4kPL2NkpZpgnXPondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "IDEFon", ticker: "IDEF", name: "iShares Defense Industrials Active ETF", mint: "th3tot4SRq6jgEyJ568NEh42MM82RSJ3NkiWeNzondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "IEFon", ticker: "IEF", name: "iShares 7-10 Year Treasury Bond ETF", mint: "D4uWxzR5StYC6sTRhVts8Eboy3pmVtHeNC62dnQondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "IEFAon", ticker: "IEFA", name: "iShares Core MSCI EAFE ETF", mint: "C9J9vZ8N79GzzxFoRkPWCkGtMKU8akg4FhUk4r9ondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "IEIon", ticker: "IEI", name: "iShares 3-7 Year Treasury Bond ETF", mint: "wuzf2FDZTRbRY3ZnndMeQ38Wk9YTDGGXTA63nUyondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "IEMGon", ticker: "IEMG", name: "iShares Core MSCI Emerging Markets ETF", mint: "cdVNL7wK8mf1UCDqM6zdrziRv4hmvqWhXeTcck2ondo", kind: "etf", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "IGEBon", ticker: "IGEB", name: "iShares Investment Grade Systematic Bond ETF", mint: "feZXF2iFspS6QKE4LSXeSESRXgrtvzbE3dZSyydondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "IGVon", ticker: "IGV", name: "iShares Expanded Tech-Software ETF", mint: "jYxKRFuXr6PEkzPpf1wWF7DhLL4gxGJ95Pv2NGrondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "IJHon", ticker: "IJH", name: "iShares Core S&P MidCap ETF", mint: "cfPLN9WXD2BTkbZhRZMVXPmVSiRo44hJWRtnaC8ondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "IJSon", ticker: "IJS", name: "iShares S&P Small-Cap 600 Value ETF", mint: "v34vtrbcjDswpFDixpVFThmUWeM1RTZwtWcp5FBondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "INCEon", ticker: "INCE", name: "Franklin Income Equity Focus ETF", mint: "D8KT4Jd8qiKKTfkM8ejSKCpWGR1o3GFvnQGp5ERondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "INDAon", ticker: "INDA", name: "iShares MSCI India ETF", mint: "DBNwt3FoYCKQWdfzxKFNZ4mzuz4Jz1iRzFf7HFzondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "INODon", ticker: "INOD", name: "Innodata", mint: "nTUjRdtzGCy8FXHK8w1n11pHABX6Dc7L7WSpzdBondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "INROon", ticker: "INRO", name: "iShares US Industry Rotation Active ETF", mint: "g4kT9HEg7rN4e5ZaEGHmzpkdM8qMbsZSHJojKeCondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "INSWon", ticker: "INSW", name: "International Seaways", mint: "mV5mof9x8nDirrHwT7g16MarvHbnRvz2zN2S4Cspyon", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "INTCon", ticker: "INTC", name: "Intel", mint: "cJpUMp5R7rZ6fGeLHbHhrRuJzK9mkyKDjZqNpT3ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "INTUon", ticker: "INTU", name: "Intuit", mint: "CozoH5HBTyyeYSQxHcWpGzd4Sq5XBaKzBzvTtN3ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "IONQon", ticker: "IONQ", name: "IonQ", mint: "DDZQijTbaSd3Kas1r1bgCnHPayk8vTP8SfZWp5Tondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "IRDMon", ticker: "IRDM", name: "Iridium Communications", mint: "go6DXMdM5zHTC9G16BwAYA8rKwGRhy9M5uudNdBondo", kind: "stock", winner: "ninguno", volumeWinner: null },
  { symbol: "IRENon", ticker: "IREN", name: "Iren", mint: "13QHuepdhtJ3urNsV9i1hdL8nQoca2G7ZaLzb5FYondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "ISRGon", ticker: "ISRG", name: "Intuitive Surgical", mint: "1MGRpPrkhEsCm2GCWD3rsvEU77xTTLAzfKXeFgFondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "ITAon", ticker: "ITA", name: "iShares US Aerospace and Defense ETF", mint: "DDcAL93Urf7KrPntvKULnZoFs4Wdee1LkkJqLpjondo", kind: "etf", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "ITOTon", ticker: "ITOT", name: "iShares Core S&P Total US Stock Market ETF", mint: "CPWkMURVvcnX8hGjqCTb8i5LkzV3VSvyk7SeJi8ondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "IVVon", ticker: "IVV", name: "iShares Core S&P 500 ETF", mint: "CqW2pd6dCPG9xKZfAsTovzDsMmAGKJSDBNcwM96ondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "IWFon", ticker: "IWF", name: "iShares Russell 1000 Growth ETF", mint: "dSHPFuMMjZqt7xDYGWrexXTSkdEZAiZngqymQF2ondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "IWMon", ticker: "IWM", name: "iShares Russell 2000 ETF", mint: "dvj2kKFSyjpnyYSYppgFdAEVfgjMEoQGi9VaV23ondo", kind: "etf", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "IWNon", ticker: "IWN", name: "iShares Russell 2000 Value ETF", mint: "DX7g7WNjDpVzNK9CG81v7wb6ZbiNzYfkdzH2Xs5ondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "IYWon", ticker: "IYW", name: "iShares US Technology ETF", mint: "vr8RQPDmYQBruiYsFSV3KZyoWFEsEejxzMCdWrBondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "JAAAon", ticker: "JAAA", name: "Janus Henderson AAA CLO ETF", mint: "KZtqx9BJbpcGY7vdzhqPXM3ECKChxE5YhXaDiwRondo", kind: "etf", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "JBLon", ticker: "JBL", name: "Jabil", mint: "igWFQo1W64cQN6QUWYRXhM1UvpPuYTYtLELbDYqqqon", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "JDon", ticker: "JD", name: "JD.com", mint: "E1aUS5nyv7kaBzdQzPVJW5zfaMgoUJpKYzdnFS2ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "JNJon", ticker: "JNJ", name: "Johnson & Johnson", mint: "KUXt7LzHWSQXp5eyqMZRxWjAP6yM8BUh4LRHwiwondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "JPMon", ticker: "JPM", name: "JPMorgan Chase", mint: "E5Gczsavxcomqf6Cw1sGCKLabL1xYD2FzKxVoB4ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "KEELon", ticker: "KEEL", name: "Keel Infrastructure", mint: "kSbeWEe64qpoVb1ZSVxgRnekZ1PwGNJkLyL5gJWondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "KEYSon", ticker: "KEYS", name: "Keysight Technologies", mint: "jYcn4hHgyq1fS46YgecQY9N1gLU3sAxKA3DZVAPondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "KLACon", ticker: "KLAC", name: "KLA", mint: "149o8ppQf9SzKCKXZ4v3dzHkwumvtQSRzSEkr29uondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "KOon", ticker: "KO", name: "Coca-Cola", mint: "e6G4pfFcrdKxJuZ4YXixRFfMbpMvgXG2Mjcus71ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "KOPNon", ticker: "KOPN", name: "Kopin", mint: "eSu547weHVErV8nax42PyJzPT8JodhBfXLDp5vyondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "KWEBon", ticker: "KWEB", name: "KraneShares CSI China Internet ETF", mint: "DVPSYdqWPLvNa8afnEqa3B9eDfTTWpGyUZeXvdMondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "LASRon", ticker: "LASR", name: "nLIGHT", mint: "Z8aFb6uQJgwFJ4KYKrT8n53aP66xqihodfAu4AKondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "LECOon", ticker: "LECO", name: "Lincoln Electric", mint: "kmppRwWb2odH6D4JWj8Lq9WshMyyUeCYssWQFhiondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "LEMBon", ticker: "LEMB", name: "iShares J.P. Morgan EM Local Currency Bond ETF", mint: "teZfcA6zpP476eKzED1daqBWDtuwbk9e2Ejk2cpondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "LIon", ticker: "LI", name: "Li Auto", mint: "v12TwfofSbvVqQ5N5KGG4d3J8rtEi4BjGfn2apyondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "LINon", ticker: "LIN", name: "Linde plc", mint: "Edik9MoFp8LAXS9HNu2gRFyihwYqDqv4ZmNmVT9ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "LITon", ticker: "LIT", name: "Global X Lithium & Battery Tech ETF", mint: "syb82jXkHWbcWgxoRqrvAcoCdsAb3y1fnCYo561ondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "LITEon", ticker: "LITE", name: "Lumentum Holdings", mint: "YrquZHx3f6sXsnZZAQiVsyQfvHwLmn2XTkDiZ1uondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "LLYon", ticker: "LLY", name: "Eli Lilly", mint: "eGGxZwNSfuNKRqQLKaz2hc4QkA2mau7skyxPdj7ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "LMTon", ticker: "LMT", name: "Lockheed", mint: "EoReHwUnGGekbXFHLj5rbCVKiwWqu32GrETMfw4ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "LOWon", ticker: "LOW", name: "Lowe's", mint: "edLdFJVVR532qhcrNTJjLAmhmyV7NsctbWVokMBondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "LPTHon", ticker: "LPTH", name: "LightPath Technologies", mint: "dhEXYTmQKbYBH3wbWTMqeZZpADSRprM4jiGYbUMondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "LRCXon", ticker: "LRCX", name: "Lam Research", mint: "wFJoeEYpKg9oRhyJy6BWTT3J95gmXBLvoeikDQNondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "LSCCon", ticker: "LSCC", name: "Lattice Semiconductor", mint: "nDetEKBEk9chztCXSYNrU5F63s2RCEQCxT7BhxDondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "LUNRon", ticker: "LUNR", name: "Intuitive Machines", mint: "DiDWPZ7vQXfpaeQ8BX68XuDYeiQLv7diDxdeUpaondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "LWLGon", ticker: "LWLG", name: "Lightwave Logic", mint: "dKGNHXGsZL4GZ4UBTCjpPbaMerqe1EdZ7aFdCxHondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "MAon", ticker: "MA", name: "Mastercard", mint: "EsVHcyRxXFJCLMiuYLWhoDygrNe1BJGpYeZ17X7ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "MARAon", ticker: "MARA", name: "MARA Holdings", mint: "ETCJUmuhs5aY62xgEVWCZ5JR8KPdeXUaJz3LuC5ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "MBLYon", ticker: "MBLY", name: "Mobileye Global", mint: "eCSPcjdpdKL1546PU3RM6BXkebuKn8iH4iuMcTBondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "MCDon", ticker: "MCD", name: "McDonald's", mint: "EUbJjmDt8JA222M91bVLZs211siZ2jzbFArH9N3ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "MEIon", ticker: "MEI", name: "Methode Electronics", mint: "jiwgLgWJ8f6aEsM6hcSCrXLNnGpYfjmCVbqqAcwondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "MELIon", ticker: "MELI", name: "MercadoLibre", mint: "EWwdgGshGngcMpDV34pWZRSu5bkAuiKuKTTHKQ8ondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "METAon", ticker: "META", name: "Meta Platforms", mint: "fDxs5y12E7x7jBwCKBXGqt71uJmCWsAQ3Srkte6ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "MKSIon", ticker: "MKSI", name: "MKS Inc.", mint: "ZNkQTVtc4WRMQfVCC23PmwYX41577tPcvs2AiXAondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "MPon", ticker: "MP", name: "MP Materials", mint: "XwFm5GiKPVTvPiEbQpdc6vJbFEpsUXRMf6TcSxnondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "MRKon", ticker: "MRK", name: "Merck", mint: "bn1fb8dwzafGePqNPrM8m8cbAKQiFqeEPuZkPySondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "MRNAon", ticker: "MRNA", name: "Moderna", mint: "14VP7DvCAdBCc5XGNZkPt6zhtPzJrWWS64Koxtxyondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "MRVLon", ticker: "MRVL", name: "Marvell Technology", mint: "FovBwhoV5KQjZCdhoM6jgXYwXLX3F8vgAfvmLH7ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "MSFTon", ticker: "MSFT", name: "Microsoft", mint: "FRmH6iRkMr33DLG6zVLR7EM4LojBFAuq6NtFzG6ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "MSTRon", ticker: "MSTR", name: "MicroStrategy", mint: "FSz4ouiqXpHuGPcpacZfTzbMjScoj5FfzHkiyu2ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "MTSIon", ticker: "MTSI", name: "MACOM Technology Solutions Holdings", mint: "dAc8yWUrVra9v2PGsn3LT18oybsM62ysQ4ikWcpondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "MTZon", ticker: "MTZ", name: "MasTec", mint: "R3ywbVQ5t8LNmjQsn2Ngv43dSqyZscQwNag9G3Eondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "MUon", ticker: "MU", name: "Micron Technology", mint: "Fz9edBpaURPPzpKVRR1A8PENYDEgHqwx5D5th28ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "MXLon", ticker: "MXL", name: "MaxLinear", mint: "aGn43ed4kjATwbVqsAuwAT24XcG9xABCcyQsFpqondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "MYRGon", ticker: "MYRG", name: "MYR Group", mint: "auLvQAhUzPuy2SQBSq2T6AofPGNkR4nZ83P8pjuondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "NATon", ticker: "NAT", name: "Nordic American Tankers", mint: "mmy8WbFRNrjoDsPGqpYmzQAVu7PfGhMCdSRLxZLondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "NBISon", ticker: "NBIS", name: "Nebius Group", mint: "DiRshqNDE68bWbGdLHm1GwQ76MvWQG3af6w1NdQondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "NEARon", ticker: "NEAR", name: "iShares Short Duration Bond Active ETF", mint: "bD6TafGhPo8NaeKEyge1DrZGAPB5wxK3x4fCpqjondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "NEEon", ticker: "NEE", name: "NextEra Energy", mint: "t7eN6cGwRMFaZvsNW2SmVwkedmHtDdrxA4ycNE5ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "NEMon", ticker: "NEM", name: "Newmont", mint: "Dig28Tf1ufhCBAsjTmFkXCgcNgMqDMYj5A2rDQmondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "NETon", ticker: "NET", name: "Cloudflare", mint: "ZtAY65FCh3YB9H1wkbjRxxY5nXt9VfuTTz3Mzbuondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "NFLXon", ticker: "NFLX", name: "Netflix", mint: "g4KnPrxPLeeKkwvDmZFMtYQPM64eHeShbD55vK6ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "NIKLon", ticker: "NIKL", name: "Sprott Nickel Miners ETF", mint: "V8LRV7kWjrx6Prke9oHEHNUiR122BVtyuPciTCTondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "NIOon", ticker: "NIO", name: "NIO", mint: "yQ37dFiGAbzrb2FRAEhGNzRy5zFfoYGWYhAepFEondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "NKEon", ticker: "NKE", name: "Nike", mint: "g646pcdG2Rt5DH9WZzL7VVnVDWCCMTTrnktwE74ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "NNEon", ticker: "NNE", name: "NANO Nuclear Energy", mint: "bz2iUTXWkutnfwG32ziABcTzXoM91sdcgdiJJJdondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "NOCon", ticker: "NOC", name: "Northrop Grumman", mint: "Dm6FpQ76SsbVmAZ4NvD2mjZP7cxbw1CASr4WwCiondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "NOKon", ticker: "NOK", name: "Nokia", mint: "amE2ANm5dyG6RTkJHdtzvWcuR8ChBZCEm5Jiqwdondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "NOWon", ticker: "NOW", name: "ServiceNow", mint: "G7pTVoSECz5RQWubEnTP7AC83KHUsSyoiqYR1R2ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "NTESon", ticker: "NTES", name: "NetEase", mint: "YeK2TdPtGLAme3Phg4pb1GBN2YxKgX5UNVyD4asondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "NUEon", ticker: "NUE", name: "Nucor", mint: "mvAUPvwKPW4rbbTXkqCvcZEG45XCeRHSVcLVym8ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "NVDAon", ticker: "NVDA", name: "NVIDIA", mint: "gEGtLTPNQ7jcg25zTetkbmF7teoDLcrfTnQfmn2ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "NVMIon", ticker: "NVMI", name: "Nova", mint: "nupQ2BuCfoVeCHVLRDhTjLJanaf5cxZ81KVFqs6ondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "NVOon", ticker: "NVO", name: "Novo Nordisk", mint: "GeV7S8vjP8qdYZpdGv2Xi6e7MUMCk8NAAp2z7g5ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "NVTon", ticker: "NVT", name: "nVent Electric", mint: "Z7G1bRFYH47se4g1ppqSgtMzeJs4JjzzFPmt7iAondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "NVTSon", ticker: "NVTS", name: "Navitas Semiconductor", mint: "fXXYmrdSAwVmtNo1ZwrkxVep7BxTsusGzmUZJSPondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "OIHon", ticker: "OIH", name: "VanEck Oil Services ETF", mint: "DnvbCqRuUYssmKVRBRNwkUnptHitH4ZZTt1KVuZondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "OIIon", ticker: "OII", name: "Oceaneering International", mint: "gfTDvjLp8K5gNDFaLMvoTZWJJY6PmVQfdPaUU7eondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "OKLOon", ticker: "OKLO", name: "Oklo", mint: "m6oDLvJT7rY7M1TxuLWP3pWmAPg2cCWDQR1NKiEondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "ONon", ticker: "ON", name: "ON Semiconductor", mint: "13qtwy5fZi9Przz14pzo9xqFSr8QHmLyUpUCvP1xondo", kind: "stock", winner: "ninguno", volumeWinner: null },
  { symbol: "ONDSon", ticker: "ONDS", name: "Ondas Holdings", mint: "7qy1j4Mechfyr6uAST3djH4vk4kiEYC2cjEytXdondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "ONTOon", ticker: "ONTO", name: "Onto Innovation", mint: "aHFrgfBHMGEScG8j64cN324jeoQ4EVXLmiHxtuPondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "OPENon", ticker: "OPEN", name: "Opendoor Technologies", mint: "ou1uE526v7zmUYP2qCb2LJgfXAyWAtWS9SETtr8ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "OPRAon", ticker: "OPRA", name: "Opera", mint: "gbHFTMkuMQUy5xrgoCBdaQ2XYvNyjWAYcnRPh9Condo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "ORBXon", ticker: "ORBX", name: "Global X Space Tech ETF", mint: "t5XWftMCacS1p3xrg14ARaxgEvEM5R241kxHGqrondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "ORCLon", ticker: "ORCL", name: "Oracle", mint: "GmDADFpfwjfzZq9MfCafMDTS69MgVjtzD7Fd9a4ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "OSCRon", ticker: "OSCR", name: "Oscar Health", mint: "ThwGDsXZ6iKubWuEQjmDxGwF3bUERDGbBXvcbjFondo", kind: "stock", winner: "ninguno", volumeWinner: null },
  { symbol: "OUSTon", ticker: "OUST", name: "Ouster", mint: "aV3R9NPU6TkyA6r9NPF5bmAw5XXsjUU7r2whgBqondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "OXYon", ticker: "OXY", name: "Occidental Petroleum", mint: "1GNFMryQ6c9ZpMhgNimmsbtgYM21qnBJgRAFoNiondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "PALLon", ticker: "PALL", name: "abrdn Physical Palladium Shares ETF", mint: "P7hTXnKk2d2DyqWnefp5BSroE1qjjKpKxg9SxQqondo", kind: "etf", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "PANWon", ticker: "PANW", name: "Palo Alto Networks", mint: "M7hVQomhw4Q2D2op3HvBrZjHu9SryjNvD5haEZ1ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "PAVEon", ticker: "PAVE", name: "Global X US Infrastructure Development ETF", mint: "DsLQ18ooPjiHYuiuQ5Jz8PNCpVaKe3FhAYpvMxWondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "PBRon", ticker: "PBR", name: "Petrobras", mint: "GRciFCqJ5y2hbiD6U5mGkohY65BZTXGuGUrCqf7ondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "PCGon", ticker: "PCG", name: "PG&E", mint: "UP5s1srLaHDc4SwJqLPa3A48x5R7ofN3hZWxWEZondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "PDBCon", ticker: "PDBC", name: "Invesco Optimum Yld Dvsfd Cmd Str No K-1 ETF", mint: "M6agiXbNgy8Xon9ngiW4ZDPbMFcNCTMkMMkshZyondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "PDDon", ticker: "PDD", name: "PDD Holdings", mint: "PnjETBCLC318DRejo9cMQKAmET9PvW8AEFGWMNtondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "PENGon", ticker: "PENG", name: "Penguin Solutions", mint: "dWFwjcUKdc7bPH9GEebpJVmEmUjvQTgEWGVR9WYondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "PEPon", ticker: "PEP", name: "PepsiCo", mint: "gud6b3fYekjhMG5F818BALwbg2vt4JKoow59Md9ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "PFEon", ticker: "PFE", name: "Pfizer", mint: "Gwh9fPsX1qWATXy63vNaJnAFfwebWQtZaVmPko6ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "PGon", ticker: "PG", name: "Procter & Gamble", mint: "GZ8v4NdSG7CTRZqHMgNsTPRULeVi8CpdWd9wZY8ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "PINSon", ticker: "PINS", name: "Pinterest", mint: "sxyg1VTSzy5zYANUK7hntNtmFAWoXGJq95AcHuVondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "PLon", ticker: "PL", name: "Planet Labs", mint: "aq2zXUHqx7Zk6HSJH2GYsNajQJZj9f3dV7gAzfuondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "PLTRon", ticker: "PLTR", name: "Palantir Technologies", mint: "HfsnTS5qtdStwec9DfBrunRqnAMYMMz1kjv9Hu9ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "PLUGon", ticker: "PLUG", name: "Plug Power", mint: "TnfswqdE1jAJ8sfnf5J7kSVLEH1cfpAYZ8MWmKfondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "POWIon", ticker: "POWI", name: "Power Integrations", mint: "ZifkbVBh94FSETjAfoLw587nxmGsYtXayAAUQgzondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "POWLon", ticker: "POWL", name: "Powell Industries", mint: "fRFzaZfGSXPf2r4oBgBBXpisRovMaJZjv1aCQBsondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "PPLTon", ticker: "PPLT", name: "abrdn Physical Platinum Shares ETF", mint: "DwRtkbsaQMGAS3oMeEGYh6M5vH4X9WECsQgqHjAondo", kind: "etf", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "PRIMon", ticker: "PRIM", name: "Primoris Services", mint: "kcc5QzXDCQ61qQ5Nbpi2RppnRSzhG1XQNXkjXwoondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "PURRon", ticker: "PURR", name: "Hyperliquid Strategies", mint: "rsiKbHCdsvmExvDfkYWypAXFsqKz6V8XuoxbkHtondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "PWRon", ticker: "PWR", name: "Quanta Services", mint: "f1yQz2fo7S24NqrsfaWDkmQ8xoa8yU72c9rEEBdondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "PYPLon", ticker: "PYPL", name: "PayPal", mint: "hM7B3UQTTR81mS27SxDDPzBbjejmo8fnpFjzgv9ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "QBTSon", ticker: "QBTS", name: "D-Wave Quantum", mint: "hqJXutLF6f7DxStrWCrnZDfXzbNTZmvi3KheVi6ondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "QCOMon", ticker: "QCOM", name: "Qualcomm", mint: "hrmX7MV5hifoaBVjnrdpz698yABxrbBNAcWtWo9ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "QLTAon", ticker: "QLTA", name: "iShares Aaa - A Rated Corporate Bond ETF", mint: "fkznXN9GALK7f9zVr2RwRHWCPhwoima4zB3JbbNondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "QQQon", ticker: "QQQ", name: "Invesco QQQ", mint: "HrYNm6jTQ71LoFphjVKBTdAE4uja7WsmLG8VxB8ondo", kind: "etf", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "QTUMon", ticker: "QTUM", name: "Defiance Quantum ETF", mint: "iJAAwDNzJHbgKm5pksL3kXHc3zZewYm37dsZNCPondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "QUBTon", ticker: "QUBT", name: "Quantum Computing", mint: "E4YowrHx5wm4RtSjfuvTqtNH3Wf7NEj5tYZGD9Bondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "QYLDon", ticker: "QYLD", name: "Global X NASDAQ 100 Covered Call ETF", mint: "ueEYw3Djy9GVu9mrP6jum8qNpxshgcy7gMfmntWondo", kind: "etf", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "RDDTon", ticker: "RDDT", name: "Reddit", mint: "HXFrTf9v9NdjGUTnx4sojR3Cf92hoBsQFUxKTN7ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "RDWon", ticker: "RDW", name: "Redwire", mint: "E6KSaqjvqe2HiUpbEweRxLK4RimQddigm95H9Jaondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "REGNon", ticker: "REGN", name: "Regeneron Pharmaceuticals", mint: "E86mX2yb3HLbJM6gRtZQ6dCYmLh6MSDZadu9SCPondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "REMXon", ticker: "REMX", name: "VanEck Rare Earth and Strategic Metals ETF", mint: "tiitb2Z1HtpB2DpVr6V7tdCFS3jmTinLeuGj9EVondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "RGTIon", ticker: "RGTI", name: "Rigetti Computing", mint: "dwEPNKQab3iwRmjGvZPXhAmws1W5NsQGwuXwi8oondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "RIOTon", ticker: "RIOT", name: "Riot Platforms", mint: "i6f3DvZBuLpnGSqS8x6WPeStJ7jNe5KewD6afD5ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "RIVNon", ticker: "RIVN", name: "Rivian Automotive", mint: "AXRsYFt7TXNQ3DcY6BkvRgPV6VsYMURyDtaeudjondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "RKLBon", ticker: "RKLB", name: "Rocket Lab", mint: "E9VQY3VnrpVSekFByzRmfeK1kxgM3UiKCoVVbdUondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "RMBSon", ticker: "RMBS", name: "Rambus", mint: "jjnSEAsi8UbCez7x9XCbWntLWRHBdc2tWSdC3uoondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "ROKon", ticker: "ROK", name: "Rockwell Automation", mint: "e83tWWrVsVk1hRGNz5BCwNr9TMBNWixmoUhWgYcondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "RTXon", ticker: "RTX", name: "RTX", mint: "12BvLZtzjdssAycxPeBQUjukhmgQpULAvy6SroYdondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "RXRXon", ticker: "RXRX", name: "Recursion Pharmaceuticals", mint: "q16ZLSbANUhpcq15pRUXRxNFfEqgpde9mSBwRcyondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "SAPon", ticker: "SAP", name: "SAP", mint: "bjbrNi96mXAzgvxSuGJ2SRJ5U4N8agbG7wUAKAjondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "SATAon", ticker: "SATA", name: "Strive Preferred", mint: "vZVGEJfSM1hS4XdFVAZL2Fr1cbPzJty9vWyax68ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "SBETon", ticker: "SBET", name: "SharpLink Gaming", mint: "iLDu2jjp2i3Uqc2Vm7K7GLiUj3hR4Un49MtD7c4ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "SBUXon", ticker: "SBUX", name: "Starbucks", mint: "iPFqjcZQTNMNXA4kbShbMhfAVD8yr8Uq9UtXMV6ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "SCCOon", ticker: "SCCO", name: "Southern Copper", mint: "EANjzFjj3nPXHdzN5CE3Z8LLVn69Ce77FE8X4cvondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "SCHWon", ticker: "SCHW", name: "Charles Schwab", mint: "cnc6M1zXLdrGR5LAQVcaJDfgezMiVWNtGQsVy1Kondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "SECUon", ticker: "SECU", name: "iShares Securitized Income Active ETF", mint: "sDtEN5uwUJJCFJ95x2rPjPqNx5UWUbHQ2ucceUzondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "SEDGon", ticker: "SEDG", name: "SolarEdge Technologies", mint: "EAwP9LGNjTkQ2YeKE6CGKqBYtrJ6APFvRe7KCMmondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "SGOVon", ticker: "SGOV", name: "iShares 0-3 Month Treasury Bond ETF", mint: "HjrN6ChZK2QRL6hMXayjGPLFvxhgjwKEy135VRjondo", kind: "etf", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "SHLDon", ticker: "SHLD", name: "Global X Defense Tech ETF", mint: "siVse6kjZb9ihaXHaqoG3mhHyTPEnNCkvSDTheoondo", kind: "etf", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "SHOPon", ticker: "SHOP", name: "Shopify", mint: "ivdDracs2s7jCP698dJXKSEQdVrNj9hasJL1Uq1ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "SHYon", ticker: "SHY", name: "iShares 1-3 Year Treasury Bond ETF", mint: "EEy57xbaLcUrN1HXj2vz8VWxeWFK1eZQZo4aWbrondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "SILon", ticker: "SIL", name: "Global X Silver Miners ETF", mint: "uiSLmtLdqxtbQq5gkwYBvBrZpnSNXZn8h6sjLsDondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "SKHYon", ticker: "SKHY", name: "SK Hynix", mint: "Huyb2fyDDjSuDKCRWsN9ci2rmcgPo6NFiLbx9ZDondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "SLBon", ticker: "SLB", name: "SLB", mint: "i7ZS13SF6BCKbzvLujp2UqLNMgM1XVnZ7A7wC6tondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "SLVon", ticker: "SLV", name: "iShares Silver Trust", mint: "iy11ytbSGcUnrjE6Lfv78TFqxKyUESfku1FugS9ondo", kind: "etf", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "SMCIon", ticker: "SMCI", name: "Super Micro Computer", mint: "jLca79XzcewRuBZyaJxVxuKpUHcEix1X4CP1RP9ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "SMRon", ticker: "SMR", name: "NuScale Power", mint: "bGy2covWNf5qyzoNdV1pWXuLmFi6Dq927o7JXzWondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "SNAPon", ticker: "SNAP", name: "Snap", mint: "a2cXfonVgQ6cKB4Lm8YZsPry39VZSA562bwmRSiondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "SNDKon", ticker: "SNDK", name: "SanDisk", mint: "EJmUVvDqAdfH5zEohkdS4234bi3c6iunqEMobjmondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "SNOWon", ticker: "SNOW", name: "Snowflake", mint: "JmFLCBwoNvcXy6B2VqABg6m784ubkXpaEx3p7S5ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "SOon", ticker: "SO", name: "Southern", mint: "aKzjn2ZdWySSGPSSDTY2HUpcSCmemSahTXihrpyondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "SOFIon", ticker: "SOFI", name: "SoFi Technologies", mint: "mqL8yXQpeSvc7NgrAtLLPtRvUiWyLoG5RWLv16iondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "SOUNon", ticker: "SOUN", name: "SoundHound AI", mint: "vE2qArmjto6VfeMngyGAnzp2ipLYeXsxiARDnnXondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "SOXQon", ticker: "SOXQ", name: "Invesco PHLX Semiconductor ETF", mint: "io3eLhnjT1a94JpzAUMWKqwMYHZRwvtGXjkkXsPondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "SOXXon", ticker: "SOXX", name: "iShares Semiconductor ETF", mint: "EN5pHc1LccUSojxb7kkyQi7v7iJN5RpDq6qz3DHondo", kind: "etf", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "SPCXon", ticker: "SPCX", name: "SpaceX", mint: "wzAyQTorWyoVXuJKj2x8EqKEGJpS13z6EWE9z5Aondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "SPGIon", ticker: "SPGI", name: "S&P Global", mint: "JrTYw7A9jihX5TwpRStYviEbsYf2X2VJpZ13719ondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "SPOTon", ticker: "SPOT", name: "Spotify", mint: "jzCvs2Pk8tDcfsFRqnEMjurgaQW4iQfEkandUR8ondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "SPYon", ticker: "SPY", name: "SPDR S&P 500 ETF", mint: "k18WJUULWheRkSpSquYGdNNmtuE2Vbw1hpuUi92ondo", kind: "etf", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "STLDon", ticker: "STLD", name: "Steel Dynamics", mint: "n7DwzSkv1SBkcA9qj8LU9sZ9sRn72Z6spU2w2b9ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "STMon", ticker: "STM", name: "STMicroelectronics", mint: "bM2VSRfbYPt29YRD9F2wTCSCSQaHtNCuz1znNDCondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "STNGon", ticker: "STNG", name: "Scorpio Tankers", mint: "mFyszXnJf8BFR8H4o33pCZS1T36BH9LjtG3gTpdondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "STRCon", ticker: "STRC", name: "Strategy STRC Preferred", mint: "y6kSRF4i9tfMMjZziPHtQE1PeUS6bWEHTzZMFgXondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "STXon", ticker: "STX", name: "Seagate", mint: "EXtprP1wzrNo2bByrU9JyzqEg2hQMSCVJakeHHYondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "SWKSon", ticker: "SWKS", name: "Skyworks Solutions", mint: "iJtKb1CWnWdgJhs7HgSZvLmSJABGGMc97QeuG7tondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "SYMon", ticker: "SYM", name: "Symbotic", mint: "nP42LxpSZkUfnBUxiFsHxL5GKYWRZ1VxqGkMTNwondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "SYSBon", ticker: "SYSB", name: "iShares Systematic Bond ETF", mint: "5U9o49BoQNU6bBMswvmBs3R4GZmYSyrnTN4ncX4ondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "Ton", ticker: "T", name: "AT&T", mint: "WKMZummev5UcXz5nNKQZvTD6QjNSM2X58uwmDReondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "TASKon", ticker: "TASK", name: "TaskUs", mint: "nQysX1ZsRJ8yTJg8smZTZ91rWcVBabDRqdUEKZHondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "TCOMon", ticker: "TCOM", name: "Trip.com Group", mint: "9PMjLqd8zPdKkJUXarnit5t7tPL3cCscwHzy7ATondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "TELon", ticker: "TEL", name: "TE Connectivity", mint: "ZjYCwYeG85TbV5oXkCkvWQTNPh2PgTQ8X4nxpbyondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "TENon", ticker: "TEN", name: "Tsakos Energy Navigation", mint: "micfqeFfvD9iDKKzuqRHXerFxG8K5VfY8CgrcQoondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "TERon", ticker: "TER", name: "Teradyne", mint: "ahvtJqt6pkzjnYTMaCKrvjPQszSKyWraiXKvuWKondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "TIPon", ticker: "TIP", name: "iShares TIPS Bond ETF", mint: "k6BPp2Xmf2TYgrZiUyWfUoZBKeqaDbvPoAVgSx2ondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "TLNon", ticker: "TLN", name: "Talen Energy", mint: "RTb54gpqAx6RpLAHRGnqQ3ciQ845CHqhg21ZzEJondo", kind: "stock", winner: "ninguno", volumeWinner: null },
  { symbol: "TLTon", ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF", mint: "KaSLSWByKy6b9FrCYXPEJoHmLpuFZtTCJk1F1Z9ondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "TMon", ticker: "TM", name: "Toyota", mint: "kbmF7ERJWMaaDswMprrH9gHSLya5D2RMBNgKqg3ondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "TMOon", ticker: "TMO", name: "Thermo Fisher Scientific", mint: "T699bgtXQw4CJ59rQ4VzLsupVQUzoL5RmuhHnKrondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "TMUSon", ticker: "TMUS", name: "T-Mobile US", mint: "pDY4GPJfZcNETPG7myXeafQfgJqqVkn81bMYDyfondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "TNKon", ticker: "TNK", name: "Teekay Tankers", mint: "mPAqB3y5N7fWmEh1BoVtrLhZKBkQe7LjBCrYUNbondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "TSEMon", ticker: "TSEM", name: "Tower Semiconductor", mint: "cRx9VtwwPTZbVk1DjbMyKzrMWn7nJA22UpMyzFYondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "TSLAon", ticker: "TSLA", name: "Tesla", mint: "KeGv7bsfR4MheC1CkmnAVceoApjrkvBhHYjWb67ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "TSMon", ticker: "TSM", name: "Taiwan Semiconductor Manufacturing", mint: "keybg184d4vyXeQdFqs4o99YsMg7xBthxTJ6Ky3ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "TTon", ticker: "TT", name: "Trane Technologies", mint: "erp2t2My8UoFgyRt39EmnnSiDUwUM5aNKw5piBKondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "TTMIon", ticker: "TTMI", name: "TTM Technologies", mint: "kWmjV2XdK5tbV6kZrM8grS6EGFmuH5i5HFW3YyLondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "TXNon", ticker: "TXN", name: "Texas Instruments", mint: "81xLFvCzFaUM3KDxSHC75pXu3RPCeSeCbmGBY8aondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "UAMYon", ticker: "UAMY", name: "United States Antimony", mint: "nbwNoPaFYNY2c3u4iK6U59ySC2ehFrpjdpfbyLDondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "UBERon", ticker: "UBER", name: "Uber", mint: "KJNeFW3kk3ycPjXpC6cbuyckjeYHacc2ekhtAi5ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "UCTTon", ticker: "UCTT", name: "Ultra Clean Holdings", mint: "jCPs1JpVKAwevND3jzeDGAUBBFkJ5TUtiu2SxLbondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "UECon", ticker: "UEC", name: "Uranium Energy", mint: "EYo8D3cLdF1CDeGms5M5VHyU52HJYinkMZ1cqvYondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "UMCon", ticker: "UMC", name: "United Microelectronics", mint: "ieocA48cBX3oiVECgosMGxG649wnf7R8EkVrA5fondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "UNGon", ticker: "UNG", name: "US Natural Gas Fund", mint: "Es2ipHL7qXBcLmZ4N7LP9PHBHaWaTMTAkxDwGGjondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "UNHon", ticker: "UNH", name: "UnitedHealth", mint: "kPBGL8vAwKN3UGmr9cjkM2dU79SC3nzTC9yu7F8ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "UNPon", ticker: "UNP", name: "Union Pacific Corporation", mint: "EvsME8gdnEwPLbTnhrGVDwrY35zBuB8hEGCq59Hondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "URAon", ticker: "URA", name: "Global X Uranium ETF", mint: "EvzskrQ3vUUkiMGG1DzfSDyG6H2WCMy3v9G8fzzondo", kind: "etf", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "URNMon", ticker: "URNM", name: "Sprott Uranium Miners ETF", mint: "hieZTEZNBU67bMGULK9hWCB9h5jBPKdpRWiXpwkondo", kind: "etf", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "USARon", ticker: "USAR", name: "USA Rare Earth", mint: "aA1dRckexLmQyppFoWmjKDFjrNFUsZeGzZ7L5xpondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "USFRon", ticker: "USFR", name: "WisdomTree Floating Rate Treasury Fund", mint: "o6U1Sm6Vd7EofMyCrL28mrp2QLzgYGgjveHiEQ5ondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "USHYon", ticker: "USHY", name: "iShares Broad USD High Yield Corporate Bond ETF", mint: "aau4XCAZR6p9uC4vgdHdh4ip3oW5pr5PrNs3FJ8ondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "USOon", ticker: "USO", name: "United States Oil Fund", mint: "rpydAzWdCy85HEmoQkH5PVxYtDYQWjmLxgHHadxondo", kind: "etf", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "UUUUon", ticker: "UUUU", name: "Energy Fuels", mint: "ey16y4Bk92zmPSvbRznuv3RioAXbVreBkQxrKGDondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "Von", ticker: "V", name: "Visa", mint: "kxEW4oJL75K37VeXaZF1ynbHQATQwhECQKN1374ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "VCXon", ticker: "VCX", name: "Fundrise Innovation Fund", mint: "esgtAV7yKf7Ei3Q92VmXcEGkoqY2UqCHzZvCWhgondo", kind: "etf", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "VDEon", ticker: "VDE", name: "Vanguard Energy ETF", mint: "hKVpWfYwP1VJ9BcBTPRcovcSpEkvnaN8eXwFoCMondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "VFSon", ticker: "VFS", name: "VinFast Auto", mint: "F3V1fKLKv7H8aNdt9TC6GQ3X4LayEfGHsPi8Umaondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "VICRon", ticker: "VICR", name: "Vicor", mint: "f9nfUo4SdhCGfHmm81m3ArgDsatwo2jLjEcgCcYondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "VNQon", ticker: "VNQ", name: "Vanguard Real Estate ETF", mint: "F3dMJ9H137YUNc9cpN3gBWDSq4MSRbTFtojH65Uondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "VPGon", ticker: "VPG", name: "Vishay Precision Group", mint: "dYF78b65HS62V3pku2uYFyektYzAhx9YACv4hWfondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "VRSNon", ticker: "VRSN", name: "VeriSign", mint: "ja4bMvHL3Hw9Ey33VGWyDeXvrHvQWyBnK4GSmCUondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "VRTon", ticker: "VRT", name: "Vertiv", mint: "MkN2TZSYTFBdMRLf9EVcfhstTwnazH8knd9hpepondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "VRTXon", ticker: "VRTX", name: "Vertex Pharmaceuticals", mint: "FL7QzUq58pvkDxkftJm7RqRWgqYEFZwXuvAMsUnondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "VSHon", ticker: "VSH", name: "Vishay Intertechnology", mint: "jbzBdFNddeEiJXGcVH4DE2qUyYfTtyY2vaHJDEZondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "VSTon", ticker: "VST", name: "Vistra", mint: "h6MW8GFpfzxFa1JNn6hZNnBF3t4fj9SHAXKy6LXondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "VTIon", ticker: "VTI", name: "Vanguard Total Stock Market ETF", mint: "jCCU4GwukjNxAXJowG2S4KCrr5g6YyUB61WHYvGondo", kind: "etf", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "VTVon", ticker: "VTV", name: "Vanguard Value ETF", mint: "KuiYLPVq65qixD9TgvxBC576C4gG6vVTCdbh2zFondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "VZon", ticker: "VZ", name: "Verizon", mint: "igu1coP6n3GPaWmbd8J9Z7UAyLpV254uQFFNfydondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "WCCon", ticker: "WCC", name: "WESCO International", mint: "m3m2HAANsAf2Y3BkdBixDgtrrFHnZDp4NqVh9obondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "WDCon", ticker: "WDC", name: "Western Digital", mint: "FLqH2jB2DZPJP5nnVFAakRKaNTcDZtq71Pnpp6Aondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "WENon", ticker: "WEN", name: "Wendy's", mint: "QwJ619MuDRvT1f29RH7tMdaqsUnaSNcvBEJAZkHondo", kind: "stock", winner: "ninguno", volumeWinner: null },
  { symbol: "WFCon", ticker: "WFC", name: "Wells Fargo", mint: "L6ZE5qCpVVSqLePz64CrwkgyWoPF9M7tB8BeFH4ondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "WLKon", ticker: "WLK", name: "Westlake", mint: "mrNSd1y72F7Dx2Uip4vidtsJKKd8iJatTKGX6Pvondo", kind: "stock", winner: "ninguno", volumeWinner: null },
  { symbol: "WMon", ticker: "WM", name: "Waste Management", mint: "FPvKvWzSzDZqgYmSZUetrkpUXSwo2VtpR4BynVYondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "WMBon", ticker: "WMB", name: "Williams", mint: "bvjmEwQBqbMr6rnx5a74boBz6nmA1DNThujPnNAondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "WMTon", ticker: "WMT", name: "Walmart", mint: "LZddqAqKqJW9oMZSjTxCUmbmzBRQtv9gMkD9hZ3ondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "WOLFon", ticker: "WOLF", name: "Wolfspeed", mint: "Zfb5PTVfGa8AV6VxrTQJuP8CjMXFPMVkVVNpcAWondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "WSon", ticker: "WS", name: "Worthington Steel", mint: "ZpJpMhWKCr4m9ZzxApJJwDc5cHiHp2hG1RZdJyvondo", kind: "stock", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "WULFon", ticker: "WULF", name: "Terawulf", mint: "exYfSJt6Fgfhfnp3bAD4roYy97hLF9npjYaLyEXondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "WYFIon", ticker: "WYFI", name: "WhiteFiber", mint: "jtnRMv1U3bJHQCsi47E6Lf8Nzkaqsisef7SkHBgondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "XOMon", ticker: "XOM", name: "Exxon Mobil", mint: "qCYD74QnXzd9pzv6pGHQKJVwoibL6sNcPQDnpDiondo", kind: "stock", winner: "xstocks", volumeWinner: "xstocks" },
  { symbol: "XYLDon", ticker: "XYLD", name: "Global X S&P 500 Covered Call ETF", mint: "wCr7YFeYDWyYSebsoMY75g8c9pguGeVB3rT6kYjondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
  { symbol: "XYZon", ticker: "XYZ", name: "Block", mint: "BWxe2FVciUbwrCUZQPUKiREBh5LmVa5AiUqNLAkondo", kind: "stock", winner: "ondo", volumeWinner: "ondo" },
  { symbol: "YEARon", ticker: "YEAR", name: "AB Ultra Short Income ETF", mint: "wxPFbh4dVrTWPGHHbVVeTHH7GK2uQwnTm5C8X3Fondo", kind: "etf", winner: "ondo (solo Ondo)", volumeWinner: "ondo" },
];

export const ONDO_MINTS: Set<string> = new Set(ONDO_TICKERS.map((entry) => entry.mint));

export const ONDO_BY_MINT: Map<string, OndoEntry> = new Map(ONDO_TICKERS.map((entry) => [entry.mint, entry]));

export const ONDO_BY_SYMBOL: Map<string, OndoEntry> = new Map(ONDO_TICKERS.map((entry) => [entry.symbol.toLowerCase(), entry]));

export const ONDO_EXCLUDED_SYMBOLS: readonly string[] = ["AIon","PSQon","SQQQon","SOXLon","SOXSon","TQQQon"];

export const ONDO_COUNTS = {"included":444,"ondoWinsBoth":212,"onlyOndo":192,"excluded":6} as const;
