-- Maverlang — registro con Supabase Auth.
-- YA APLICADA en el proyecto actual (2026-10-06). Sólo para un proyecto nuevo:
-- Pegar UNA vez en el SQL Editor de un proyecto vacío.
-- No pegues 0001_init.sql antes: ese esquema usa ids de texto (Privy) y choca con esta tabla.
-- Idempotente: se puede volver a ejecutar.
-- No crea órdenes ni cartera: eso sigue en mock.

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  nombre text,
  rut text,
  pais text,
  fecha_nacimiento date,
  telefono text,
  is_us_person boolean not null default false,
  onboarding_completed boolean not null default false,
  language text not null default 'es-CL',
  display_currency text not null default 'CLP',
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now(),
  constraint profiles_nombre_len check (nombre is null or char_length(btrim(nombre)) between 1 and 80),
  constraint profiles_pais_iso check (pais is null or pais ~ '^[A-Z]{2}$'),
  constraint profiles_telefono_e164 check (telefono is null or telefono ~ '^\+[1-9][0-9]{7,14}$'),
  constraint profiles_language check (language in ('es-CL', 'en')),
  constraint profiles_currency check (display_currency in ('CLP', 'USD'))
);

create table if not exists public.consents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  doc text not null check (doc in ('terminos', 'privacidad', 'riesgos')),
  version text not null check (char_length(btrim(version)) > 0),
  accepted_at timestamptz not null default pg_catalog.now(),
  unique (user_id, doc, version)
);

create table if not exists public.preferences (
  user_id uuid primary key references public.profiles (id) on delete cascade,
  notify_orders boolean not null default true,
  notify_deposits boolean not null default true,
  notify_news boolean not null default false,
  updated_at timestamptz not null default pg_catalog.now()
);

create or replace function public.rut_valido(raw text)
returns boolean
language plpgsql
immutable
set search_path = ''
as $$
declare
  clean text;
  body text;
  dv text;
  expected text;
  total int := 0;
  factor int := 2;
  i int;
  digit int;
  resto int;
begin
  if raw is null then
    return false;
  end if;
  clean := upper(replace(replace(btrim(raw), '.', ''), '-', ''));
  if clean !~ '^[0-9]{7,8}[0-9K]$' then
    return false;
  end if;
  body := substring(clean from 1 for char_length(clean) - 1);
  dv := substring(clean from char_length(clean) for 1);
  for i in reverse char_length(body)..1 loop
    digit := ascii(substring(body from i for 1)) - ascii('0');
    total := total + digit * factor;
    factor := case when factor = 7 then 2 else factor + 1 end;
  end loop;
  resto := 11 - (total % 11);
  expected := case
    when resto = 11 then '0'
    when resto = 10 then 'K'
    else resto::text
  end;
  return dv = expected;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_rut_valido'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_rut_valido
      check (rut is null or public.rut_valido(rut));
  end if;
end $$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := pg_catalog.now();
  return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  meta jsonb := coalesce(new.raw_user_meta_data, '{}'::jsonb);
  nombre text := nullif(btrim(meta->>'nombre'), '');
  rut text := nullif(btrim(meta->>'rut'), '');
  pais text := upper(nullif(btrim(meta->>'pais'), ''));
  nacimiento date;
  telefono text := nullif(btrim(meta->>'telefono'), '');
  us_flag text := lower(coalesce(meta->>'is_us_person', 'false'));
  us_person boolean := us_flag in ('true', 't', '1', 'yes');
  terms text := nullif(btrim(meta->>'terms_version'), '');
  privacy text := nullif(btrim(meta->>'privacy_version'), '');
  risks text := nullif(btrim(meta->>'risks_version'), '');
  completo boolean := false;
begin
  begin
    nacimiento := nullif(meta->>'fecha_nacimiento', '')::date;
  exception
    when others then
      nacimiento := null;
  end;

  if pais = 'US' or us_person then
    raise exception 'registro_us_person' using errcode = '42501';
  end if;

  if nombre is not null and char_length(nombre) > 80 then
    nombre := null;
  end if;
  if pais is not null and pais !~ '^[A-Z]{2}$' then
    pais := null;
  end if;
  if telefono is null or telefono !~ '^\+[1-9][0-9]{7,14}$' then
    telefono := null;
  end if;
  if rut is not null and not public.rut_valido(rut) then
    rut := null;
  end if;
  if pais is distinct from 'CL' then
    rut := null;
  end if;

  completo :=
    nombre is not null
    and pais is not null
    and nacimiento is not null
    and nacimiento <= (current_date - interval '18 years')::date
    and telefono is not null
    and (pais is distinct from 'CL' or rut is not null)
    and terms is not null
    and privacy is not null
    and risks is not null;

  insert into public.profiles (
    id,
    email,
    nombre,
    rut,
    pais,
    fecha_nacimiento,
    telefono,
    is_us_person,
    onboarding_completed,
    language,
    display_currency
  ) values (
    new.id,
    new.email,
    nombre,
    rut,
    pais,
    nacimiento,
    telefono,
    false,
    completo,
    'es-CL',
    'CLP'
  )
  on conflict (id) do nothing;

  if terms is not null then
    insert into public.consents (user_id, doc, version)
    values (new.id, 'terminos', terms)
    on conflict (user_id, doc, version) do nothing;
  end if;
  if privacy is not null then
    insert into public.consents (user_id, doc, version)
    values (new.id, 'privacidad', privacy)
    on conflict (user_id, doc, version) do nothing;
  end if;
  if risks is not null then
    insert into public.consents (user_id, doc, version)
    values (new.id, 'riesgos', risks)
    on conflict (user_id, doc, version) do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_user();

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
  before update on public.profiles
  for each row
  execute function public.set_updated_at();

drop trigger if exists preferences_set_updated_at on public.preferences;
create trigger preferences_set_updated_at
  before update on public.preferences
  for each row
  execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.consents enable row level security;
alter table public.preferences enable row level security;

drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own
  on public.profiles
  for select
  to authenticated
  using ((select auth.uid()) = id);

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own
  on public.profiles
  for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

drop policy if exists consents_select_own on public.consents;
create policy consents_select_own
  on public.consents
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists consents_insert_own on public.consents;
create policy consents_insert_own
  on public.consents
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists preferences_select_own on public.preferences;
create policy preferences_select_own
  on public.preferences
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists preferences_insert_own on public.preferences;
create policy preferences_insert_own
  on public.preferences
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists preferences_update_own on public.preferences;
create policy preferences_update_own
  on public.preferences
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

revoke all on table public.profiles from public, anon, authenticated;
grant select, update on table public.profiles to authenticated;

revoke all on table public.consents from public, anon, authenticated;
grant select, insert on table public.consents to authenticated;

revoke all on table public.preferences from public, anon, authenticated;
grant select, insert, update on table public.preferences to authenticated;

revoke all on sequence public.consents_id_seq from public, anon, authenticated;
grant usage, select on sequence public.consents_id_seq to authenticated;

revoke all on function public.handle_new_user() from public, anon, authenticated;
revoke all on function public.set_updated_at() from public, anon, authenticated;
revoke all on function public.rut_valido(text) from public, anon, authenticated;
grant execute on function public.set_updated_at() to authenticated;
grant execute on function public.rut_valido(text) to authenticated;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'supabase_auth_admin') then
    grant execute on function public.handle_new_user() to supabase_auth_admin;
  end if;
end $$;
