-- Maverlang — cumplimiento geográfico y declaración de no ser U.S. person (M75).
-- NO APLICADA. La pega el operador en el SQL Editor DESPUÉS de 0011.
-- Idempotente: se puede volver a ejecutar.
-- Fechas con now() / current_date. Sin pg_catalog.current_date.
--
-- [REVISIÓN ABOGADO] lista provisoria (la misma que config/compliance.ts):
-- US, PR, GU, VI, AS, MP, UM, CA, GB, AU, CU, IR, KP, SY, RU, BY.
-- El entorno sólo puede sumar países; esta lista no se achica desde aquí.
--
-- Lo que hace:
-- 1. Columnas en profiles: residence_country, nationality_country,
--    us_person_declared_at, us_person_declaration_version.
--    is_us_person ya existe desde 0002: no se vuelve a crear.
-- 2. Esas columnas no las cambia `authenticated` después del onboarding
--    (trigger, como el de columnas sensibles de 0009). service_role pasa.
-- 3. consents acepta el doc `us_person` (versión de la declaración).
-- 4. public.compliance_events (cambios e intentos bloqueados): RLS sin
--    políticas y sin grants para anon/authenticated.
-- 5. handle_new_user (lógica de 0009) también guarda la declaración y
--    rechaza el alta si residencia, nacionalidad o is_us_person están
--    bloqueados (no se crea la cuenta).

-- 1. Columnas. is_us_person ya está en 0002.
alter table public.profiles add column if not exists residence_country text;
alter table public.profiles add column if not exists nationality_country text;
alter table public.profiles add column if not exists us_person_declared_at timestamptz;
alter table public.profiles add column if not exists us_person_declaration_version text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_residence_country_iso'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_residence_country_iso
      check (residence_country is null or residence_country ~ '^[A-Z]{2}$');
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_nationality_country_iso'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_nationality_country_iso
      check (nationality_country is null or nationality_country ~ '^[A-Z]{2}$');
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_us_person_version_len'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_us_person_version_len
      check (
        us_person_declaration_version is null
        or char_length(btrim(us_person_declaration_version)) > 0
      );
  end if;
end $$;

-- 2. El doc de la declaración entra en consents. El check inline de 0002
-- se llama consents_doc_check; si el nombre difiere, se busca por el texto.
do $$
declare
  cname text;
begin
  select con.conname into cname
  from pg_constraint con
  where con.conrelid = 'public.consents'::regclass
    and con.contype = 'c'
    and pg_get_constraintdef(con.oid) ilike '%terminos%'
    and pg_get_constraintdef(con.oid) ilike '%doc%'
  limit 1;
  if cname is not null then
    execute format('alter table public.consents drop constraint %I', cname);
  end if;
end $$;

alter table public.consents drop constraint if exists consents_doc_check;
alter table public.consents
  add constraint consents_doc_check
  check (doc in ('terminos', 'privacidad', 'riesgos', 'us_person'));

-- 3. Eventos de cumplimiento. Sin políticas: nadie desde el navegador.
create table if not exists public.compliance_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  type text not null check (char_length(btrim(type)) > 0),
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.compliance_events enable row level security;
revoke all on table public.compliance_events from public, anon, authenticated;
revoke all on sequence public.compliance_events_id_seq from public, anon, authenticated;

-- 4. Después del onboarding, authenticated no mueve estas columnas.
create or replace function public.reject_profiles_compliance_change()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  locked text[] := array[
    'residence_country',
    'nationality_country',
    'is_us_person',
    'us_person_declared_at',
    'us_person_declaration_version'
  ];
  col text;
  old_val jsonb;
  new_val jsonb;
  caller_role text := coalesce((auth.jwt() ->> 'role'), '');
begin
  if caller_role in ('service_role', 'supabase_auth_admin') then
    return new;
  end if;
  if coalesce(old.onboarding_completed, false) is not true then
    return new;
  end if;
  old_val := to_jsonb(old);
  new_val := to_jsonb(new);
  foreach col in array locked loop
    if (old_val ? col) and (new_val ? col)
      and (old_val -> col is distinct from new_val -> col) then
      raise exception 'cambio_no_permitido: %', col;
    end if;
  end loop;
  return new;
end;
$$;

drop trigger if exists profiles_reject_compliance_change on public.profiles;
create trigger profiles_reject_compliance_change
  before update on public.profiles
  for each row
  execute function public.reject_profiles_compliance_change();

revoke all on function public.reject_profiles_compliance_change() from public, anon, authenticated;

-- 5. Al quedar escrita la versión, se guarda el consentimiento y un evento.
-- security definer: compliance_events no tiene grant para authenticated.
create or replace function public.record_us_person_declaration()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if new.us_person_declaration_version is null then
    return new;
  end if;
  if tg_op = 'UPDATE'
    and old.us_person_declaration_version is not distinct from new.us_person_declaration_version
    and old.us_person_declared_at is not distinct from new.us_person_declared_at
    and old.residence_country is not distinct from new.residence_country
    and old.nationality_country is not distinct from new.nationality_country
    and old.is_us_person is not distinct from new.is_us_person then
    return new;
  end if;

  insert into public.consents (user_id, doc, version, accepted_at)
  values (
    new.id,
    'us_person',
    new.us_person_declaration_version,
    coalesce(new.us_person_declared_at, now())
  )
  on conflict (user_id, doc, version) do nothing;

  insert into public.compliance_events (user_id, type, data)
  values (
    new.id,
    'us_person_declaration',
    jsonb_build_object(
      'version', new.us_person_declaration_version,
      'residence_country', new.residence_country,
      'nationality_country', new.nationality_country,
      'is_us_person', new.is_us_person
    )
  );

  return new;
end;
$$;

drop trigger if exists profiles_record_us_person_declaration on public.profiles;
create trigger profiles_record_us_person_declaration
  after insert or update on public.profiles
  for each row
  execute function public.record_us_person_declaration();

revoke all on function public.record_us_person_declaration() from public, anon, authenticated;

-- 6. handle_new_user: misma lógica que 0009, más la declaración.
-- Si el país o la nacionalidad están en la lista, el alta aborta (42501)
-- y no queda usuario ni perfil.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  meta jsonb := coalesce(new.raw_user_meta_data, '{}'::jsonb);
  nombre text := nullif(btrim(meta->>'nombre'), '');
  rut text := nullif(btrim(meta->>'rut'), '');
  pais text := upper(nullif(btrim(meta->>'pais'), ''));
  nationality text := upper(nullif(btrim(meta->>'nationality_country'), ''));
  declaration_version text := nullif(btrim(meta->>'us_person_declaration_version'), '');
  nacimiento date;
  telefono text := nullif(btrim(meta->>'telefono'), '');
  us_flag text := lower(coalesce(meta->>'is_us_person', 'false'));
  us_person boolean := us_flag in ('true', 't', '1', 'yes');
  terms text := nullif(btrim(meta->>'terms_version'), '');
  privacy text := nullif(btrim(meta->>'privacy_version'), '');
  risks text := nullif(btrim(meta->>'risks_version'), '');
  accepted_raw text := nullif(btrim(meta->>'terms_accepted_at'), '');
  accepted_at timestamptz := now();
  completo boolean := false;
  blocked text[] := array['US','PR','GU','VI','AS','MP','UM','CA','GB','AU','CU','IR','KP','SY','RU','BY'];
begin
  begin
    nacimiento := nullif(meta->>'fecha_nacimiento', '')::date;
  exception
    when others then
      nacimiento := null;
  end;

  if accepted_raw is not null then
    begin
      if accepted_raw::timestamptz <= now() then
        accepted_at := accepted_raw::timestamptz;
      end if;
    exception
      when others then
        accepted_at := now();
    end;
  end if;

  if pais = any (blocked) or nationality = any (blocked) or us_person then
    raise exception 'registro_us_person' using errcode = '42501';
  end if;

  if nombre is not null and char_length(nombre) > 80 then
    nombre := null;
  end if;
  if pais is not null and pais !~ '^[A-Z]{2}$' then
    pais := null;
  end if;
  if nationality is not null and nationality !~ '^[A-Z]{2}$' then
    nationality := null;
  end if;
  if telefono is null or telefono !~ '^\+[1-9][0-9]{7,14}$' then
    telefono := null;
  end if;
  if rut is not null and not public.rut_valido(rut) then
    rut := null;
  end if;
  if pais is distinct from 'CL' then
    rut := null;
  end if;

  completo :=
    nombre is not null
    and pais is not null
    and nacimiento is not null
    and nacimiento <= (current_date - interval '18 years')::date
    and telefono is not null
    and (pais is distinct from 'CL' or rut is not null)
    and terms is not null
    and privacy is not null
    and risks is not null;

  insert into public.profiles (
    id,
    email,
    nombre,
    rut,
    pais,
    fecha_nacimiento,
    telefono,
    is_us_person,
    residence_country,
    nationality_country,
    us_person_declared_at,
    us_person_declaration_version,
    onboarding_completed,
    language,
    display_currency
  ) values (
    new.id,
    new.email,
    nombre,
    rut,
    pais,
    nacimiento,
    telefono,
    false,
    pais,
    nationality,
    case when declaration_version is not null then now() else null end,
    declaration_version,
    completo,
    'es-CL',
    'CLP'
  )
  on conflict (id) do nothing;

  if terms is not null then
    insert into public.consents (user_id, doc, version, accepted_at)
    values (new.id, 'terminos', terms, accepted_at)
    on conflict (user_id, doc, version) do nothing;
  end if;
  if privacy is not null then
    insert into public.consents (user_id, doc, version, accepted_at)
    values (new.id, 'privacidad', privacy, accepted_at)
    on conflict (user_id, doc, version) do nothing;
  end if;
  if risks is not null then
    insert into public.consents (user_id, doc, version, accepted_at)
    values (new.id, 'riesgos', risks, accepted_at)
    on conflict (user_id, doc, version) do nothing;
  end if;

  return new;
end;
$$;
